language: php

matrix:
  fast_finish: true

  include:
    - php: 5.5
    - php: 5.6
    - php: 7

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer install
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit
  - >
    echo;
    echo "Running PHP CS Fixer";
    .Build/bin/php-cs-fixer fix --dry-run --config=.php_cs.dist --diff --format=txt --path-mode=intersection --using-cache=no --verbose ./
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
